In [1]:
import pandas as pd


df_row = pd.read_csv("FoodFacts.products.170k_May26.csv")

C:\Users\Dev\AppData\Local\Temp\ipykernel_29140\1939381940.py:4: DtypeWarning: Columns (0,1,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,445,446,447,448,449,450,451,452,453,454,455,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508) have mixed types. Specify dtype option on import or set low_memory=False.
  df_row = pd.read_csv("FoodFacts.products.170k_May26.csv")

In [2]:
print("Shape:", df_row.shape)

print("\nColumns:")
print(df_row.columns.tolist())

print("\nTarget Distribution:")
print(df_row["ecoscore_grade"].value_counts(dropna=False))

Shape: (171490, 509)

Columns:
['_id', 'product_name_en', 'ecoscore_grade', 'ingredients_text_en', 'categories', 'categories_hierarchy[0]', 'categories_hierarchy[1]', 'categories_hierarchy[2]', 'categories_hierarchy[3]', 'categories_hierarchy[4]', 'categories_hierarchy[5]', 'categories_hierarchy[6]', 'categories_hierarchy[7]', 'categories_hierarchy[8]', 'categories_hierarchy[9]', 'categories_hierarchy[10]', 'categories_hierarchy[11]', 'categories_hierarchy[12]', 'categories_hierarchy[13]', 'categories_hierarchy[14]', 'categories_hierarchy[15]', 'categories_hierarchy[16]', 'categories_hierarchy[17]', 'categories_hierarchy[18]', 'categories_hierarchy[19]', 'categories_hierarchy[20]', 'categories_hierarchy[21]', 'categories_hierarchy[22]', 'categories_hierarchy[23]', 'categories_hierarchy[24]', 'categories_hierarchy[25]', 'categories_hierarchy[26]', 'categories_hierarchy[27]', 'categories_hierarchy[28]', 'categories_hierarchy[29]', 'categories_hierarchy[30]', 'categories_hierarchy[31]', 'categories_hierarchy[32]', 'categories_hierarchy[33]', 'categories_hierarchy[34]', 'categories_hierarchy[35]', 'categories_hierarchy[36]', 'categories_hierarchy[37]', 'categories_hierarchy[38]', 'categories_hierarchy[39]', 'categories_hierarchy[40]', 'categories_hierarchy[41]', 'Unnamed: 47', 'Unnamed: 48', 'countries_hierarchy[0]', 'countries_hierarchy[1]', 'countries_hierarchy[2]', 'countries_hierarchy[3]', 'countries_hierarchy[4]', 'countries_hierarchy[5]', 'countries_hierarchy[6]', 'countries_hierarchy[7]', 'countries_hierarchy[8]', 'countries_hierarchy[9]', 'countries_hierarchy[10]', 'countries_hierarchy[11]', 'countries_hierarchy[12]', 'countries_hierarchy[13]', 'countries_hierarchy[14]', 'countries_hierarchy[15]', 'countries_hierarchy[16]', 'countries_hierarchy[17]', 'countries_hierarchy[18]', 'countries_hierarchy[19]', 'countries_hierarchy[20]', 'countries_hierarchy[21]', 'countries_hierarchy[22]', 'countries_hierarchy[23]', 'countries_hierarchy[24]', 'countries_hierarchy[25]', 'countries_hierarchy[26]', 'countries_hierarchy[27]', 'ingredients_hierarchy[0]', 'ingredients_hierarchy[1]', 'ingredients_hierarchy[2]', 'ingredients_hierarchy[3]', 'ingredients_hierarchy[4]', 'ingredients_hierarchy[5]', 'ingredients_hierarchy[6]', 'ingredients_hierarchy[7]', 'ingredients_hierarchy[8]', 'ingredients_hierarchy[9]', 'ingredients_hierarchy[10]', 'ingredients_hierarchy[11]', 'ingredients_hierarchy[12]', 'ingredients_hierarchy[13]', 'ingredients_hierarchy[14]', 'ingredients_hierarchy[15]', 'ingredients_hierarchy[16]', 'ingredients_hierarchy[17]', 'ingredients_hierarchy[18]', 'ingredients_hierarchy[19]', 'ingredients_hierarchy[20]', 'ingredients_hierarchy[21]', 'ingredients_hierarchy[22]', 'ingredients_hierarchy[23]', 'ingredients_hierarchy[24]', 'ingredients_hierarchy[25]', 'ingredients_hierarchy[26]', 'ingredients_hierarchy[27]', 'ingredients_hierarchy[28]', 'ingredients_hierarchy[29]', 'ingredients_hierarchy[30]', 'ingredients_hierarchy[31]', 'ingredients_hierarchy[32]', 'ingredients_hierarchy[33]', 'ingredients_hierarchy[34]', 'ingredients_hierarchy[35]', 'ingredients_hierarchy[36]', 'ingredients_hierarchy[37]', 'ingredients_hierarchy[38]', 'ingredients_hierarchy[39]', 'ingredients_hierarchy[40]', 'ingredients_hierarchy[41]', 'ingredients_hierarchy[42]', 'ingredients_hierarchy[43]', 'ingredients_hierarchy[44]', 'ingredients_hierarchy[45]', 'ingredients_hierarchy[46]', 'ingredients_hierarchy[47]', 'ingredients_hierarchy[48]', 'ingredients_hierarchy[49]', 'ingredients_hierarchy[50]', 'ingredients_hierarchy[51]', 'ingredients_hierarchy[52]', 'ingredients_hierarchy[53]', 'ingredients_hierarchy[54]', 'ingredients_hierarchy[55]', 'ingredients_hierarchy[56]', 'ingredients_hierarchy[57]', 'ingredients_hierarchy[58]', 'ingredients_hierarchy[59]', 'ingredients_hierarchy[60]', 'ingredients_hierarchy[61]', 'ingredients_hierarchy[62]', 'ingredients_hierarchy[63]', 'ingredients_hierarchy[64]', 'ingredients_hierarchy[65]', 'ingredients_hierarchy[66]', 'ingredients_hierarchy[67]', 'ingredients_hierarchy[68]', 'ingredients_hierarchy[69]', 'ingredients_hierarchy[70]', 'ingredients_hierarchy[71]', 'ingredients_hierarchy[72]', 'ingredients_hierarchy[73]', 'ingredients_hierarchy[74]', 'ingredients_hierarchy[75]', 'ingredients_hierarchy[76]', 'ingredients_hierarchy[77]', 'ingredients_hierarchy[78]', 'ingredients_hierarchy[79]', 'ingredients_hierarchy[80]', 'ingredients_hierarchy[81]', 'ingredients_hierarchy[82]', 'ingredients_hierarchy[83]', 'ingredients_hierarchy[84]', 'ingredients_hierarchy[85]', 'ingredients_hierarchy[86]', 'ingredients_hierarchy[87]', 'ingredients_hierarchy[88]', 'ingredients_hierarchy[89]', 'ingredients_hierarchy[90]', 'ingredients_hierarchy[91]', 'ingredients_hierarchy[92]', 'ingredients_hierarchy[93]', 'ingredients_hierarchy[94]', 'ingredients_hierarchy[95]', 'ingredients_hierarchy[96]', 'ingredients_hierarchy[97]', 'ingredients_hierarchy[98]', 'ingredients_hierarchy[99]', 'ingredients_hierarchy[100]', 'ingredients_hierarchy[101]', 'ingredients_hierarchy[102]', 'ingredients_hierarchy[103]', 'ingredients_hierarchy[104]', 'ingredients_hierarchy[105]', 'ingredients_hierarchy[106]', 'ingredients_hierarchy[107]', 'ingredients_hierarchy[108]', 'ingredients_hierarchy[109]', 'ingredients_hierarchy[110]', 'ingredients_hierarchy[111]', 'ingredients_hierarchy[112]', 'ingredients_hierarchy[113]', 'ingredients_hierarchy[114]', 'ingredients_hierarchy[115]', 'ingredients_hierarchy[116]', 'ingredients_hierarchy[117]', 'ingredients_hierarchy[118]', 'ingredients_hierarchy[119]', 'ingredients_hierarchy[120]', 'ingredients_hierarchy[121]', 'ingredients_hierarchy[122]', 'ingredients_hierarchy[123]', 'ingredients_hierarchy[124]', 'ingredients_hierarchy[125]', 'ingredients_hierarchy[126]', 'ingredients_hierarchy[127]', 'ingredients_hierarchy[128]', 'ingredients_hierarchy[129]', 'ingredients_hierarchy[130]', 'ingredients_hierarchy[131]', 'ingredients_hierarchy[132]', 'ingredients_hierarchy[133]', 'ingredients_hierarchy[134]', 'ingredients_hierarchy[135]', 'ingredients_hierarchy[136]', 'ingredients_hierarchy[137]', 'ingredients_hierarchy[138]', 'ingredients_hierarchy[139]', 'ingredients_hierarchy[140]', 'ingredients_hierarchy[141]', 'ingredients_hierarchy[142]', 'ingredients_hierarchy[143]', 'ingredients_hierarchy[144]', 'ingredients_hierarchy[145]', 'ingredients_hierarchy[146]', 'ingredients_hierarchy[147]', 'ingredients_hierarchy[148]', 'ingredients_hierarchy[149]', 'ingredients_hierarchy[150]', 'ingredients_hierarchy[151]', 'ingredients_hierarchy[152]', 'ingredients_hierarchy[153]', 'ingredients_hierarchy[154]', 'ingredients_hierarchy[155]', 'ingredients_hierarchy[156]', 'ingredients_hierarchy[157]', 'ingredients_hierarchy[158]', 'ingredients_hierarchy[159]', 'ingredients_hierarchy[160]', 'ingredients_hierarchy[161]', 'ingredients_hierarchy[162]', 'ingredients_hierarchy[163]', 'ingredients_hierarchy[164]', 'ingredients_hierarchy[165]', 'ingredients_hierarchy[166]', 'ingredients_hierarchy[167]', 'ingredients_hierarchy[168]', 'ingredients_hierarchy[169]', 'ingredients_hierarchy[170]', 'ingredients_hierarchy[171]', 'ingredients_hierarchy[172]', 'ingredients_hierarchy[173]', 'ingredients_hierarchy[174]', 'ingredients_hierarchy[175]', 'ingredients_hierarchy[176]', 'ingredients_hierarchy[177]', 'ingredients_hierarchy[178]', 'ingredients_hierarchy[179]', 'ingredients_hierarchy[180]', 'ingredients_hierarchy[181]', 'ingredients_hierarchy[182]', 'ingredients_hierarchy[183]', 'ingredients_hierarchy[184]', 'ingredients_hierarchy[185]', 'ingredients_hierarchy[186]', 'ingredients_hierarchy[187]', 'ingredients_hierarchy[188]', 'ingredients_hierarchy[189]', 'ingredients_hierarchy[190]', 'ingredients_hierarchy[191]', 'ingredients_hierarchy[192]', 'ingredients_hierarchy[193]', 'ingredients_hierarchy[194]', 'ingredients_hierarchy[195]', 'ingredients_hierarchy[196]', 'ingredients_hierarchy[197]', 'ingredients_hierarchy[198]', 'ingredients_hierarchy[199]', 'ingredients_hierarchy[200]', 'ingredients_hierarchy[201]', 'ingredients_hierarchy[202]', 'ingredients_hierarchy[203]', 'ingredients_hierarchy[204]', 'ingredients_hierarchy[205]', 'ingredients_hierarchy[206]', 'ingredients_hierarchy[207]', 'ingredients_hierarchy[208]', 'ingredients_hierarchy[209]', 'ingredients_hierarchy[210]', 'ingredients_hierarchy[211]', 'ingredients_hierarchy[212]', 'ingredients_hierarchy[213]', 'ingredients_hierarchy[214]', 'ingredients_hierarchy[215]', 'ingredients_hierarchy[216]', 'ingredients_hierarchy[217]', 'ingredients_hierarchy[218]', 'ingredients_hierarchy[219]', 'ingredients_hierarchy[220]', 'ingredients_hierarchy[221]', 'ingredients_hierarchy[222]', 'ingredients_hierarchy[223]', 'ingredients_hierarchy[224]', 'ingredients_hierarchy[225]', 'ingredients_hierarchy[226]', 'ingredients_hierarchy[227]', 'ingredients_hierarchy[228]', 'ingredients_hierarchy[229]', 'ingredients_hierarchy[230]', 'ingredients_hierarchy[231]', 'ingredients_hierarchy[232]', 'ingredients_hierarchy[233]', 'ingredients_hierarchy[234]', 'ingredients_hierarchy[235]', 'ingredients_hierarchy[236]', 'ingredients_hierarchy[237]', 'ingredients_hierarchy[238]', 'ingredients_hierarchy[239]', 'ingredients_hierarchy[240]', 'ingredients_hierarchy[241]', 'ingredients_hierarchy[242]', 'ingredients_hierarchy[243]', 'ingredients_hierarchy[244]', 'ingredients_hierarchy[245]', 'ingredients_hierarchy[246]', 'ingredients_hierarchy[247]', 'ingredients_hierarchy[248]', 'ingredients_hierarchy[249]', 'ingredients_hierarchy[250]', 'ingredients_hierarchy[251]', 'ingredients_hierarchy[252]', 'ingredients_hierarchy[253]', 'ingredients_hierarchy[254]', 'ingredients_hierarchy[255]', 'ingredients_hierarchy[256]', 'ingredients_hierarchy[257]', 'ingredients_hierarchy[258]', 'ingredients_hierarchy[259]', 'ingredients_hierarchy[260]', 'ingredients_hierarchy[261]', 'ingredients_hierarchy[262]', 'ingredients_hierarchy[263]', 'ingredients_hierarchy[264]', 'ingredients_hierarchy[265]', 'ingredients_hierarchy[266]', 'ingredients_hierarchy[267]', 'ingredients_hierarchy[268]', 'ingredients_hierarchy[269]', 'ingredients_hierarchy[270]', 'ingredients_hierarchy[271]', 'ingredients_hierarchy[272]', 'ingredients_hierarchy[273]', 'ingredients_hierarchy[274]', 'ingredients_hierarchy[275]', 'ingredients_hierarchy[276]', 'ingredients_hierarchy[277]', 'ingredients_hierarchy[278]', 'ingredients_hierarchy[279]', 'ingredients_hierarchy[280]', 'ingredients_hierarchy[281]', 'ingredients_hierarchy[282]', 'ingredients_hierarchy[283]', 'ingredients_hierarchy[284]', 'ingredients_hierarchy[285]', 'ingredients_hierarchy[286]', 'ingredients_hierarchy[287]', 'ingredients_hierarchy[288]', 'ingredients_hierarchy[289]', 'ingredients_hierarchy[290]', 'ingredients_hierarchy[291]', 'ingredients_hierarchy[292]', 'ingredients_hierarchy[293]', 'ingredients_hierarchy[294]', 'ingredients_hierarchy[295]', 'ingredients_hierarchy[296]', 'ingredients_hierarchy[297]', 'ingredients_hierarchy[298]', 'ingredients_hierarchy[299]', 'ingredients_hierarchy[300]', 'ingredients_hierarchy[301]', 'ingredients_hierarchy[302]', 'ingredients_hierarchy[303]', 'ingredients_hierarchy[304]', 'ingredients_hierarchy[305]', 'ingredients_hierarchy[306]', 'ingredients_hierarchy[307]', 'ingredients_hierarchy[308]', 'ingredients_hierarchy[309]', 'ingredients_hierarchy[310]', 'ingredients_hierarchy[311]', 'ingredients_hierarchy[312]', 'ingredients_hierarchy[313]', 'ingredients_hierarchy[314]', 'ingredients_hierarchy[315]', 'ingredients_hierarchy[316]', 'ingredients_hierarchy[317]', 'ingredients_hierarchy[318]', 'ingredients_hierarchy[319]', 'ingredients_hierarchy[320]', 'ingredients_hierarchy[321]', 'ingredients_hierarchy[322]', 'ingredients_hierarchy[323]', 'ingredients_hierarchy[324]', 'ingredients_hierarchy[325]', 'ingredients_hierarchy[326]', 'ingredients_hierarchy[327]', 'ingredients_hierarchy[328]', 'ingredients_hierarchy[329]', 'ingredients_hierarchy[330]', 'ingredients_hierarchy[331]', 'ingredients_hierarchy[332]', 'ingredients_hierarchy[333]', 'ingredients_hierarchy[334]', 'ingredients_hierarchy[335]', 'ingredients_hierarchy[336]', 'ingredients_hierarchy[337]', 'ingredients_hierarchy[338]', 'ingredients_hierarchy[339]', 'ingredients_hierarchy[340]', 'ingredients_hierarchy[341]', 'ingredients_hierarchy[342]', 'ingredients_hierarchy[343]', 'ingredients_hierarchy[344]', 'ingredients_hierarchy[345]', 'ingredients_hierarchy[346]', 'ingredients_hierarchy[347]', 'ingredients_hierarchy[348]', 'ingredients_hierarchy[349]', 'ingredients_hierarchy[350]', 'ingredients_hierarchy[351]', 'ingredients_hierarchy[352]', 'ingredients_hierarchy[353]', 'ingredients_hierarchy[354]', 'ingredients_hierarchy[355]', 'ingredients_hierarchy[356]', 'ingredients_hierarchy[357]', 'ingredients_hierarchy[358]', 'ingredients_hierarchy[359]', 'ingredients_hierarchy[360]', 'ingredients_hierarchy[361]', 'ingredients_hierarchy[362]', 'ingredients_hierarchy[363]', 'ingredients_hierarchy[364]', 'origins_hierarchy[0]', 'origins_hierarchy[1]', 'origins_hierarchy[2]', 'origins_hierarchy[3]', 'origins_hierarchy[4]', 'origins_hierarchy[5]', 'origins_hierarchy[6]', 'origins_hierarchy[7]', 'origins_hierarchy[8]', 'origins_hierarchy[9]', 'origins_hierarchy[10]', 'origins_hierarchy[11]', 'origins_hierarchy[12]', 'origins_hierarchy[13]', 'packaging_hierarchy[0]', 'packaging_hierarchy[1]', 'packaging_hierarchy[2]', 'packaging_hierarchy[3]', 'packaging_hierarchy[4]', 'packaging_hierarchy[5]', 'packaging_hierarchy[6]', 'packaging_hierarchy[7]', 'packaging_hierarchy[8]', 'packaging_hierarchy[9]', 'packaging_hierarchy[10]', 'packaging_hierarchy[11]', 'packaging_hierarchy[12]', 'packaging_hierarchy[13]', 'packaging_hierarchy[14]', 'packaging_hierarchy[15]', 'packaging_hierarchy[16]', 'packaging_hierarchy[17]', 'packaging_hierarchy[18]', 'packaging_hierarchy[19]', 'packaging_hierarchy[20]', 'packaging_hierarchy[21]', 'packaging_hierarchy[22]', 'packaging_hierarchy[23]', 'packaging_hierarchy[24]', 'packaging_hierarchy[25]', 'packaging_hierarchy[26]', 'packaging_hierarchy[27]', 'packaging_hierarchy[28]', 'packaging_hierarchy[29]', 'packaging_hierarchy[30]', 'packaging_hierarchy[31]', 'packaging_hierarchy[32]', 'packaging_hierarchy[33]', 'packaging_hierarchy[34]', 'packaging_hierarchy[35]', 'packaging_hierarchy[36]', 'packaging_hierarchy[37]', 'packaging_hierarchy[38]', 'packaging_hierarchy[39]', 'packaging_hierarchy[40]', 'packaging_hierarchy[41]', 'packaging_hierarchy[42]', 'packaging_hierarchy[43]', 'packaging_hierarchy[44]', 'packaging_hierarchy[45]', 'packaging_hierarchy[46]', 'packaging_hierarchy[47]', 'packaging_hierarchy[48]', 'packaging_hierarchy[49]', 'packaging_hierarchy[50]', 'packaging_hierarchy[51]', 'packaging_hierarchy[52]']

Target Distribution:
ecoscore_grade
d         49480
b         34570
c         25989
e         24354
a         23288
f         10102
a-plus     3707
Name: count, dtype: int64

In [3]:
missing = (
    df_row.isnull().sum()
    .sort_values(ascending=False)
)

print(missing.head(30))

Unnamed: 48                   171490
Unnamed: 47                   171490
ingredients_hierarchy[299]    171489
ingredients_hierarchy[300]    171489
ingredients_hierarchy[297]    171489
ingredients_hierarchy[298]    171489
ingredients_hierarchy[303]    171489
ingredients_hierarchy[304]    171489
ingredients_hierarchy[305]    171489
ingredients_hierarchy[306]    171489
ingredients_hierarchy[307]    171489
ingredients_hierarchy[308]    171489
ingredients_hierarchy[309]    171489
ingredients_hierarchy[310]    171489
ingredients_hierarchy[311]    171489
ingredients_hierarchy[312]    171489
ingredients_hierarchy[313]    171489
ingredients_hierarchy[314]    171489
ingredients_hierarchy[315]    171489
ingredients_hierarchy[316]    171489
ingredients_hierarchy[301]    171489
ingredients_hierarchy[302]    171489
ingredients_hierarchy[318]    171489
ingredients_hierarchy[317]    171489
ingredients_hierarchy[321]    171489
ingredients_hierarchy[319]    171489
ingredients_hierarchy[322]    171489
countries_hierarchy[20]       171489
countries_hierarchy[21]       171489
ingredients_hierarchy[320]    171489
dtype: int64

In [4]:
print(df_row['categories'].head(10))

0    Beverages and beverages preparations, Beverage...
1    Dranken en drankbereidingen,Dranken,Alcoholisc...
2                                             Biscuits
3                                      Green tapenades
4                                     Chocolate Cookie
5    Alimentos y bebidas de origen vegetal, Aliment...
6    Plant-based foods and beverages, Plant-based f...
7    Dairies, Desserts, Dairy desserts, fr:cremes-b...
8    Plant-based foods and beverages, Plant-based f...
9    Plant-based foods and beverages, Plant-based f...
Name: categories, dtype: object

In [5]:
print(df_row['categories'].sample(10, random_state=42))

11471     Snacks, Sweet snacks, Biscuits and cakes, Cake...
40178     Snacks, Snacks sucrés, Cacao et dérivés, Choco...
28971     Snacks,Sweet snacks,Cocoa and its products,Cho...
136286    en:Breakfasts, en:Spreads, en:Sweet spreads, e...
9293      Plant-based foods and beverages, Plant-based f...
166680                       Dairies, Milks, en:whole-milks
67987                                    Sweeteners, Sugars
144395    Alimentos y bebidas de origen vegetal, Aliment...
100107    Plant-based foods and beverages, Plant-based f...
124486                Condiments, Sauces, Sauces à la crème
Name: categories, dtype: object

In [6]:
df_row['categories'].isnull().sum()

np.int64(5)

In [7]:
ingredient_cols = [
    c for c in df_row.columns
    if 'ingredients_hierarchy[' in c
]

In [8]:
category_cols = [
    c for c in df_row.columns
    if 'categories_hierarchy[' in c
]

In [9]:
print(len(ingredient_cols))
print(len(category_cols))

365
42

In [10]:
def merge_hierarchy(row):

    values = []

    for item in row:

        if pd.notnull(item):

            item = str(item)

            item = item.replace('en:', '')
            item = item.replace('-', ' ')
            item = item.strip()

            if item:
                values.append(item)

    values = list(dict.fromkeys(values))

    return ' '.join(values)

In [11]:
df_row['ingredient_hierarchy_text'] = (
    df_row[ingredient_cols]
    .apply(merge_hierarchy, axis=1)
)
df_row['category_hierarchy_text'] = (
    df_row[category_cols]
    .apply(merge_hierarchy, axis=1)
)

In [12]:
print(df_row['ingredient_hierarchy_text'].head())
print("*"*50)
print(df_row['category_hierarchy_text'].head())

0    sugar added sugar disaccharide whole milk dair...
1
2
3
4                                                  dog
Name: ingredient_hierarchy_text, dtype: object
**************************************************
0    beverages and beverages preparations plant bas...
1    beverages and beverages preparations beverages...
2      snacks sweet snacks biscuits and cakes biscuits
3     spreads salted spreads tapenades green tapenades
4    snacks sweet snacks biscuits and cakes biscuit...
Name: category_hierarchy_text, dtype: object

In [13]:
print(
    df_row[
        [
            'product_name_en',
            'ingredients_text_en',
            'categories',
            'ingredient_hierarchy_text',
            'category_hierarchy_text'
        ]
    ].isnull().sum()
)

product_name_en              58008
ingredients_text_en          97165
categories                       5
ingredient_hierarchy_text        0
category_hierarchy_text          0
dtype: int64

In [14]:
(
    df_row['ingredient_hierarchy_text']
    .str.strip()
    .eq('')
    .sum()
)

np.int64(69651)

In [15]:
(
    df_row['category_hierarchy_text']
    .str.strip()
    .eq('')
    .sum()
)

np.int64(5)

In [16]:
df_row["_id"].value_counts()

_id
4056490000000.0    1493
4088600000000.0    1254
5000170000000.0     925
7613310000000.0     836
4099200000000.0     796
                   ...
0225805024741         1
3.87009E+12           1
0056910864126         1
2.35183E+12           1
5.09986E+12           1
Name: count, Length: 100242, dtype: int64

In [17]:
(
    (
        df_row['product_name_en'].fillna('').str.strip() == ''
    ) &
    (
        df_row['ingredients_text_en'].fillna('').str.strip() == ''
    ) &
    (
        df_row['categories'].fillna('').str.strip() == ''
    ) &
    (
        df_row['ingredient_hierarchy_text'].fillna('').str.strip() == ''
    ) &
    (
        df_row['category_hierarchy_text'].fillna('').str.strip() == ''
    )
).sum()

np.int64(2)

In [18]:
df_row[['_id', 'product_name_en']].head(20)

                _id                                    product_name_en
0   7896010000000.0                                                123
1   8410390000000.0                                               2022
2   8901060000000.0                                               5050
3   4004200000000.0                                        5.00017E+12
4   5203060000000.0                                        5.20306E+12
5   7771260000000.0                                        7.77126E+12
6        26173184.0                                   Asparagus Spears
7        25279269.0                                      Creme Brûlée
8   3045320000000.0                                     Peach Conserve
9   9415080000000.0                                       pitted dates
10    11110831668.0                                         pure honey
11   810395026048.0  !Holla Nolla!, Bon Temps!, Real Restaurant Tor...
12   626570626671.0                                 "river rat" cheese
13   202200509608.0                    "vampire slayer" garlic cheddar
14   850210008934.0                             # No Filter Beauty tea
15    76592300033.0                       #1 Pita Bread 14 Jack Junior
16  7613310000000.0                                 #Taste smoking hot
17    41497097548.0                          %1 Low Fat Chocolate Milk
18    75243101760.0                                     %1 lowfat milk
19  5060370000000.0                         & Nut Smooth Peanut Butter

In [19]:
df_nlp = df_row[
    [
        'ecoscore_grade',
        'product_name_en',
        'ingredients_text_en',
        'categories',
        'ingredient_hierarchy_text',
        'category_hierarchy_text'
    ]
].copy()

In [20]:
df_nlp[
    df_nlp['ingredient_hierarchy_text']
    .astype(str)
    .str.fullmatch(r'e\d+[a-z]*', na=False)
].shape

(33, 6)

In [21]:
df_row[
    df_row['ingredient_hierarchy_text']
    .astype(str)
    .str.fullmatch(r'[\d\.Ee\+\-]+', na=False)
][['_id', 'ingredient_hierarchy_text']].head(20)

                   _id ingredient_hierarchy_text
1348   5010510000000.0                      e150
2935    733739064110.0                      e406
3438    788269179391.0                      e123
3537    858320000077.0                      e967
9614   5054070000000.0                      e500
33110   858982001740.0                      e968
33111   858982001733.0                      e968
33112   856923007493.0                      e968
38273   194346050864.0                      e428
38582  8809730000000.0                      e415
39994  7039010000000.0                      e428
41310  5000270000000.0                      e150
43364    78742241913.0                      e428
49301    34000479795.0                      e420
54061  3073780000000.0                      440e
57679   790011140672.0                      e551
71276  9345240000000.0                      e412
71659   858982001795.0                      e968
72290      547404828.0                      e330
85507  4061460000000.0                      e385

In [22]:
(
    df_row["ingredient_hierarchy_text"]
    .fillna('')
    .astype(str)
    .str.fullmatch(r'[\d\.Ee\+\-]+')
    .sum()
)

np.int64(37)

In [23]:
df_row = df_row[
    ~(
        (
            df_row['product_name_en'].fillna('').str.strip() == ''
        ) &
        (
            df_row['ingredients_text_en'].fillna('').str.strip() == ''
        ) &
        (
            df_row['categories'].fillna('').str.strip() == ''
        ) &
        (
            df_row['ingredient_hierarchy_text'].fillna('').str.strip() == ''
        ) &
        (
            df_row['category_hierarchy_text'].fillna('').str.strip() == ''
        )
    )
].copy()

In [24]:
print(df_nlp.shape)

(171490, 6)

In [25]:
print(df_nlp.sample(5, random_state=42))

       ecoscore_grade                    product_name_en  \
11471               c                  Blueberry muffins
40178               d              GIANDOR CRISPY NOUGAT
28971               e  Dark Chocolate Bar -  With Coffee
136286              b                                NaN
9293                c    Belvita Soft Baked Banana Bread

                                      ingredients_text_en  \
11471                                                 NaN
40178                                                 NaN
28971   Coffee, cacao liquor, organic sugar, cacao but...
136286                                                NaN
9293    whole grain blend (cracked buckwheat, rolled o...

                                               categories  \
11471   Snacks, Sweet snacks, Biscuits and cakes, Cake...
40178   Snacks, Snacks sucrés, Cacao et dérivés, Choco...
28971   Snacks,Sweet snacks,Cocoa and its products,Cho...
136286  en:Breakfasts, en:Spreads, en:Sweet spreads, e...
9293    Plant-based foods and beverages, Plant-based f...

                                ingredient_hierarchy_text  \
11471
40178   sugar added sugar disaccharide cocoa butter pl...
28971   coffee cacao liquor sugar added sugar disaccha...
136286
9293    whole grain blend flour canola oil oil and fat...

                                  category_hierarchy_text
11471   snacks sweet snacks biscuits and cakes cakes m...
40178   snacks sweet snacks cocoa and its products cho...
28971   snacks sweet snacks cocoa and its products cho...
136286  breakfasts spreads sweet spreads bee products ...
9293    plant based foods and beverages plant based fo...

In [26]:
df_nlp

,ecoscore_grade,product_name_en,ingredients_text_en,categories,ingredient_hierarchy_text,category_hierarchy_text
0,f,123,NaN,"Beverages and beverages preparations, Beverage...",sugar added sugar disaccharide whole milk dair...,beverages and beverages preparations plant bas...
1,e,2022,NaN,"Dranken en drankbereidingen,Dranken,Alcoholisc...",,beverages and beverages preparations beverages...
2,c,5050,NaN,Biscuits,,snacks sweet snacks biscuits and cakes biscuits
3,c,5.00017E+12,NaN,Green tapenades,,spreads salted spreads tapenades green tapenades
4,d,5.20306E+12,dog,Chocolate Cookie,dog,snacks sweet snacks biscuits and cakes biscuit...
...,...,...,...,...,...,...
171485,d,NaN,NaN,Salted butters,,dairies fats spreads spreadable fats animal fa...
171486,e,NaN,NaN,"it:Burro, en:butters",it:materia grassa,dairies spreads fats animal fats spreadable fa...
171487,d,NaN,NaN,Fruit smoothies,ru:пюре киви ru:сок ананасовый прямого отжима ...,plant based foods and beverages beverages plan...
171488,b,NaN,NaN,Oliven,de:grüne nocellara del belice oliven vegetable...,plant based foods and beverages plant based fo...
171489,e,NaN,NaN,"Leches,Leche en polvo,Leche-de-bebe",,beverages dairies dried products milks dried p...

In [27]:
print(df_nlp['product_name_en'].sample(10, random_state=1).tolist())

[nan, 'House 74% cocoa', 'Colby Jack Natural Cheese', nan, 'Tea section, organic green tea, pineapple orange strawberry', nan, nan, 'Rich Caramel Milk Chocolate Bar', 'Pomegranate Delight', 'Stoneridge, cheese cellar, green olive havarti cheese']

In [28]:
print(df_nlp['ingredients_text_en'].sample(10, random_state=1).tolist())

[nan, nan, 'Cultured pasteurized milk, salt, enzymes, annatto (color).', nan, 'Organic green tea, pineapple, orange and strawberry flavors', nan, nan, 'Cane Sugar, Cocoa Butter, Whole Milk Powder, Cocoa Mass, Sunflower Lecithin, Vanilla Powder, Caramel With Salted Butter (Glucose Syrup, Sugar, Sweetened Condensed Milk, Water,Salted Butter, Cream, Salt), Thickeners: Pectin, Carrageenan.', "water, sugar, ';concentrated fruit juices [concentrated pomegranate juice ('3.4%), concentrated apple juice (1.1%), concentrated red grape juice (0.7%), concentrated aronia berry juice], acidity regulator (330), iodised salt, stabilizers (466, 440), sweetener (960). contains added flavour (natural and nature identical flavouring substances).", 'Pasteurized milk, cheese culture, black or green olives, salt, enzymes']

In [29]:
print(df_nlp['categories'].sample(10, random_state=1).tolist())

['На завтрак, Намазки, Сладкие намазки, Продукция пчеловодства, Продукты сельскохозяйственного производства, Подсластители и заменители сахара, Мёд, Мёд с цветочной пыльцой', 'Snacks, Sweet snacks, Cocoa and its products, Chocolates, Dark chocolates', 'Dairies, Fermented foods, Fermented milk products, Cheeses', "Aliments et boissons à base de végétaux, Aliments d'origine végétale, Petit-déjeuners, Céréales et pommes de terre, Céréales et dérivés, Céréales pour petit-déjeuner", 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags', 'Frozen mixed mushrooms', 'Alimentos e bebidas à base de plantas, Alimentos à base de plantas, Cereais e Batatas, Sementes, Cereais e seus produtos, Grãos de cereais, Arrozes', 'Milk chocolates,Caramel chocolates', 'Plant-based foods and beverages, Beverages, Plant-based beverages, Fruit-based beverages, Juices and nectars, Fruit juices', 'Dairies, Fermented foods, Fermented milk products, Cheeses']

In [30]:
print(df_nlp[['categories',
              'category_hierarchy_text']].sample(
                  10,
                  random_state=42
              ))

                                               categories  \
11471   Snacks, Sweet snacks, Biscuits and cakes, Cake...
40178   Snacks, Snacks sucrés, Cacao et dérivés, Choco...
28971   Snacks,Sweet snacks,Cocoa and its products,Cho...
136286  en:Breakfasts, en:Spreads, en:Sweet spreads, e...
9293    Plant-based foods and beverages, Plant-based f...
166680                     Dairies, Milks, en:whole-milks
67987                                  Sweeteners, Sugars
144395  Alimentos y bebidas de origen vegetal, Aliment...
100107  Plant-based foods and beverages, Plant-based f...
124486              Condiments, Sauces, Sauces à la crème

                                  category_hierarchy_text
11471   snacks sweet snacks biscuits and cakes cakes m...
40178   snacks sweet snacks cocoa and its products cho...
28971   snacks sweet snacks cocoa and its products cho...
136286  breakfasts spreads sweet spreads bee products ...
9293    plant based foods and beverages plant based fo...
166680                          dairies milks whole milks
67987                                   sweeteners sugars
144395  plant based foods and beverages plant based fo...
100107  plant based foods and beverages plant based fo...
124486                     condiments sauces cream sauces

In [31]:
df_nlp = df_row[
    [
        'ecoscore_grade',
        'product_name_en',
        'ingredients_text_en',
        'ingredient_hierarchy_text',
        'category_hierarchy_text'
    ]
].copy()

In [32]:
print(df_nlp.shape)

print(df_nlp.isnull().sum())

(171488, 5)
ecoscore_grade                   0
product_name_en              58006
ingredients_text_en          97163
ingredient_hierarchy_text        0
category_hierarchy_text          0
dtype: int64

In [33]:
(
    (
        df_nlp['product_name_en'].fillna('').str.strip() == ''
    ) &
    (
        df_nlp['ingredients_text_en'].fillna('').str.strip() == ''
    ) &
    (
        df_nlp['ingredient_hierarchy_text'].fillna('').str.strip() == ''
    ) &
    (
        df_nlp['category_hierarchy_text'].fillna('').str.strip() == ''
    )
).sum()

np.int64(0)

In [34]:
import re
import unicodedata

def clean_text_lstm(text):

    if pd.isna(text):
        return ''

    text = str(text)

    # unicode normalization
    text = unicodedata.normalize('NFKC', text)

    # remove language tags
    text = re.sub(
        r'\b(?:en|fr|de|pt|it|ru|es|nl):',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # remove urls
    text = re.sub(
        r'http\S+|www\S+',
        ' ',
        text
    )

    # replace hyphens
    text = text.replace('-', ' ')

    # remove punctuation
    text = re.sub(
        r'[^\w\s]',
        ' ',
        text
    )

    # normalize spaces
    text = re.sub(
        r'\s+',
        ' ',
        text
    ).strip()

    # lowercase
    text = text.lower()

    return text

In [35]:
text_cols = [
    'product_name_en',
    'ingredients_text_en',
    'ingredient_hierarchy_text',
    'category_hierarchy_text'
]

for col in text_cols:
    df_nlp[col] = (
        df_nlp[col]
        .fillna('')
        .apply(clean_text_lstm)
    )

In [36]:
print(df_nlp.sample(10, random_state=42))

       ecoscore_grade                  product_name_en  \
11471               c                blueberry muffins
40178               d            giandor crispy nougat
28971               e   dark chocolate bar with coffee
91096               a         selects brussels sprouts
9293                c  belvita soft baked banana bread
166680              d
67987               a                no calorie stevia
144396         a-plus
96720               b       spelt chia wholemeal bread
141425              c

                                      ingredients_text_en  \
11471
40178
28971   coffee cacao liquor organic sugar cacao butter...
91096                                    brussels sprouts
9293    whole grain blend cracked buckwheat rolled oat...
166680
67987   erythritol dextrose with maltodextrin rebiana ...
144396
96720
141425

                                ingredient_hierarchy_text  \
11471
40178   sugar added sugar disaccharide cocoa butter pl...
28971   coffee cacao liquor sugar added sugar disaccha...
91096         brussels sprouts vegetable brassica cabbage
9293    whole grain blend flour canola oil oil and fat...
166680  whole milk dairy milk acidity regulator e339i ...
67987   e968 dextrose with maltodextrin rebiana natura...
144396  orange juice from concentrate fruit citrus fru...
96720
141425

                                  category_hierarchy_text
11471   snacks sweet snacks biscuits and cakes cakes m...
40178   snacks sweet snacks cocoa and its products cho...
28971   snacks sweet snacks cocoa and its products cho...
91096   plant based foods and beverages plant based fo...
9293    plant based foods and beverages plant based fo...
166680                          dairies milks whole milks
67987                                   sweeteners sugars
144396  plant based foods and beverages beverages plan...
96720   plant based foods and beverages plant based fo...
141425  plant based foods and beverages plant based fo...

In [37]:
print(df_nlp.isnull().sum())

ecoscore_grade               0
product_name_en              0
ingredients_text_en          0
ingredient_hierarchy_text    0
category_hierarchy_text      0
dtype: int64

In [38]:
for col in [
    'product_name_en',
    'ingredients_text_en',
    'ingredient_hierarchy_text',
    'category_hierarchy_text'
]:

    non_empty = (
        df_nlp[col]
        .str.strip()
        .ne('')
        .sum()
    )

    print(col)
    print(non_empty)
    print(
        round(
            non_empty / len(df_nlp) * 100,
            2
        ),
        '%'
    )
    print()

product_name_en
113479
66.17 %

ingredients_text_en
74322
43.34 %

ingredient_hierarchy_text
101839
59.39 %

category_hierarchy_text
171485
100.0 %

In [39]:
df_nlp['deep_text'] = (
    df_nlp['product_name_en'] + ' ' +
    df_nlp['ingredients_text_en'] + ' ' +
    df_nlp['ingredient_hierarchy_text'] + ' ' +
    df_nlp['category_hierarchy_text']
)

In [40]:
print(df_nlp['deep_text'].sample(10, random_state=42))

11471     blueberry muffins   snacks sweet snacks biscui...
40178     giandor crispy nougat  sugar added sugar disac...
28971     dark chocolate bar with coffee coffee cacao li...
91096     selects brussels sprouts brussels sprouts brus...
9293      belvita soft baked banana bread whole grain bl...
166680      whole milk dairy milk acidity regulator e339...
67987     no calorie stevia erythritol dextrose with mal...
144396      orange juice from concentrate fruit citrus f...
96720     spelt chia wholemeal bread   plant based foods...
141425       plant based foods and beverages plant based...
Name: deep_text, dtype: object

In [41]:
df_nlp['deep_text'].str.split().apply(len).describe()

count    171488.000000
mean         50.855413
std          56.131310
min           2.000000
25%          16.000000
50%          30.000000
75%          66.000000
max        2080.000000
Name: deep_text, dtype: float64

In [42]:
lengths = (
    df_nlp['deep_text']
    .str.split()
    .apply(len)
)

print("90% :", lengths.quantile(0.90))
print("95% :", lengths.quantile(0.95))
print("99% :", lengths.quantile(0.99))

90% : 121.0
95% : 162.0
99% : 256.0

In [43]:
df_nlp.loc[
    lengths > 500,
    'deep_text'
].head(5)

4682    angus beef ribeye steak ribeye steak nutrition...
4808    antipasto misti prosciutto pork salt coppa di ...
4849    apetit αρετιt posni keks srb mne hr bih keks s...
6455    assorted cookies roscayema wheat flour sugar v...
8938    beef enchilada dinner tortilla corn flour grou...
Name: deep_text, dtype: object

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [45]:
label_encoder = LabelEncoder()

df_nlp['label'] = label_encoder.fit_transform(
    df_nlp['ecoscore_grade']
)

print(dict(zip(label_encoder.classes_,label_encoder.transform(   label_encoder.classes_) )))

{'a': np.int64(0), 'a-plus': np.int64(1), 'b': np.int64(2), 'c': np.int64(3), 'd': np.int64(4), 'e': np.int64(5), 'f': np.int64(6)}

In [46]:
X = df_nlp['deep_text']

y = df_nlp['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [47]:
print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts())

(137190,)
(34298,)
label
4    39584
2    27655
3    20791
5    19483
0    18630
6     8082
1     2965
Name: count, dtype: int64

In [48]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Bag of Words
bow_vectorizer = CountVectorizer(
    max_features=100000,
    ngram_range=(1,2),
    min_df=2
)

X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

# TF-IDF
tfidf_vectorizer = TfidfVectorizer(
    max_features=150000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [49]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_tfidf_smote, y_train_tfidf_smote = smote.fit_resample(
    X_train_tfidf,
    y_train
)

X_train_bow_smote, y_train_bow_smote = smote.fit_resample(
    X_train_bow,
    y_train
)

In [50]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

from sklearn.metrics import classification_report, accuracy_score


class TextClassificationModels:

    def __init__(self):
        self.models = {
            "Naive Bayes": MultinomialNB(),

            "SVM": LinearSVC(
                class_weight="balanced"
            ),

            "Logistic Regression": LogisticRegression(
                max_iter=2000,
                class_weight="balanced"
            ),

            "Random Forest": RandomForestClassifier(
                n_estimators=200,
                class_weight="balanced",
                random_state=42,
                n_jobs=-1
            ),

            "Extra Trees": ExtraTreesClassifier(
                n_estimators=200,
                class_weight="balanced",
                random_state=42,
                n_jobs=-1
            ),

            "XGBoost": XGBClassifier(
                n_estimators=300,
                max_depth=8,
                learning_rate=0.1,
                objective='multi:softmax',
                num_class=7,
                random_state=42
            )
        }

    def train_and_evaluate(self, X_train, X_test, y_train, y_test, label_encoder):

        results = {}

        for name, model in self.models.items():
            print(f"\nTraining {name}...")

            model.fit(X_train, y_train)

            y_pred = model.predict(X_test)

            acc = accuracy_score(y_test, y_pred)

            print(f"\n{name} Accuracy: {acc:.4f}")
            print(
                classification_report(
                    y_test,
                    y_pred,
                    target_names=label_encoder.classes_
                )
            )

            results[name] = acc

        return results

In [ ]:
ml_models = TextClassificationModels()

bow_results = ml_models.train_and_evaluate(
    X_train_bow,
    X_test_bow,
    y_train,
    y_test,
    label_encoder
)

Training Naive Bayes...

Naive Bayes Accuracy: 0.6979
              precision    recall  f1-score   support

           a       0.60      0.78      0.68      4658
      a-plus       0.16      0.12      0.14       741
           b       0.76      0.71      0.74      6914
           c       0.62      0.59      0.61      5198
           d       0.83      0.68      0.75      9896
           e       0.65      0.78      0.71      4871
           f       0.71      0.84      0.77      2020

    accuracy                           0.70     34298
   macro avg       0.62      0.64      0.63     34298
weighted avg       0.71      0.70      0.70     34298


Training SVM...

C:\Users\Dev\Downloads\.ipynb_checkpoints\Lib\site-packages\sklearn\svm\_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

SVM Accuracy: 0.8047
              precision    recall  f1-score   support

           a       0.81      0.76      0.78      4658
      a-plus       0.30      0.29      0.30       741
           b       0.83      0.84      0.83      6914
           c       0.75      0.73      0.74      5198
           d       0.85      0.85      0.85      9896
           e       0.79      0.84      0.81      4871
           f       0.84      0.88      0.86      2020

    accuracy                           0.80     34298
   macro avg       0.74      0.74      0.74     34298
weighted avg       0.80      0.80      0.80     34298


Training Logistic Regression...

In [ ]:
tfidf_results = ml_models.train_and_evaluate(
    X_train_tfidf,
    X_test_tfidf,
    y_train,
    y_test,
    label_encoder
)

In [ ]:
tfidf_smote_results = ml_models.train_and_evaluate(
    X_train_tfidf_smote,
    X_test_tfidf,
    y_train_tfidf_smote,
    y_test,
    label_encoder
)